### PR TITLE
[Refactor] Several refactors with no backwad compatability

### PR DESCRIPTION
**Pull request by wuzirui**
**Brief**:
1. Delete the nerfstudio dir/ in our repo and use a submodule instead. The user will have the option to install nerfstudio via `pip install nerfstudio`.
2. rename `nsg/` to `mars/`, NSGxxx ->Marsxxx
3. bump nerfstudio & pytorch version, support nerfstudio 0.3.x and torch>2.0

**TODO**
- [x] rerun the checkpoint experiments, and update the google drive

### CODE REVIEW

**Comment by xBeho1der** [comment]
1. Using `pip install nerfstudio` as in `README.md` may cause error when running `ns-install-cli`, maybe submodule is better choice.
2. `cicai_configs.py`, please change some NSG -> Mars

**Comment by xBeho1der** [comment]
<table>
<thead>
  <tr>
    <th>Dataset</th>
    <th>Scene</th>
    <th>First Frame</th>
    <th>Last Frame</th>
    <th>Setting</th>
    <th>PSNR</th>
    <th>SSIM</th>
    <th>Download</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td rowspan="4">KITTI-MOT</td>
    <td>0006</td>
    <td>5</td>
    <td>260</td>
    <td>Reconstruction</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>0006</td>
    <td>5</td>
    <td>260</td>
    <td>Novel View Synthesis 75%</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>0006</td>
    <td>5</td>
    <td>260</td>
    <td>Novel View Synthesis 50%</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>0006</td>
    <td>5</td>
    <td>260</td>
    <td>Novel View Synthesis 25%</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td rowspan="3">Vitural KITTI-2</td>
    <td>Scene06</td>
    <td>0</td>
    <td>237</td>
    <td>Novel View Synthesis 75%</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Scene06</td>
    <td>0</td>
    <td>237</td>
    <td>Novel View Synthesis 50%</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Scene06</td>
    <td>0</td>
    <td>237</td>
    <td>Novel View Synthesis 25%</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
</tbody>
</table>

**Comment by wuzirui** [comment]
Reeaaally busy recently :(
Please stay tunned.

**Comment by wuzirui** [comment]
1. delete this message 
 https://github.com/OPEN-AIR-SUN/mars/blob/51017e2c46723b16c81fd5323fd4d4e0ce14e8c8/README.md?plain=1#L21
2. update the installation guide
 https://github.com/OPEN-AIR-SUN/mars/blob/51017e2c46723b16c81fd5323fd4d4e0ce14e8c8/README.md?plain=1#L31-L57
3. add some instructions on the depth map generation
https://github.com/OPEN-AIR-SUN/mars/blob/51017e2c46723b16c81fd5323fd4d4e0ce14e8c8/README.md?plain=1#L75-L102
4. start/end frames
https://github.com/OPEN-AIR-SUN/mars/blob/51017e2c46723b16c81fd5323fd4d4e0ce14e8c8/README.md?plain=1#L193-L199

@xBeho1der

**Pull request merged**
